import typer
from typing import List, Optional

from my_model.config import WorkspaceConfig, ModelConfig

app = typer.Typer()
model_app = typer.Typer()
app.add_typer(model_app, name="model")

def _load_workspace(alias: str) -> WorkspaceConfig:
    """Load workspace configuration for given alias."""
    return WorkspaceConfig.load(alias)

@app.command()
def hello(name: str = "world"):
    """Simple hello command for testing the CLI entrypoint."""
    typer.echo(f"Hello, {name}!")

@model_app.command("add")
def model_add(
    alias: str = typer.Option(..., "--alias", "-a", help="Workspace alias"),
    provider_id: str = typer.Option(..., "--provider-id", "-p", help="Provider identifier defined in workspace"),
    model_id: str = typer.Option(..., "--model-id", "-m", help="Backend model identifier for the provider"),
    tags: List[str] = typer.Option([], "--tag", "-t", help="Tag for the model (repeatable)"),
    backend_id: Optional[str] = typer.Option(None, "--backend-id", help="Unique backend ID (optional, autogenerated)"),
):
    """Add a backend model to the workspace configuration."""
    try:
        config = _load_workspace(alias)
        if not any(p.provider_id == provider_id for p in config.providers):
            typer.echo(f"Provider '{provider_id}' not found in workspace '{alias}'.", err=True)
            raise typer.Exit(code=1)
        if not backend_id:
            backend_id = f"{provider_id}-{model_id}"
        if any(m.backend_id == backend_id for m in config.models):
            typer.echo(f"Model with backend_id '{backend_id}' already exists.", err=True)
            raise typer.Exit(code=1)

        model = ModelConfig(
            backend_id=backend_id,
            provider_id=provider_id,
            model_id=model_id,
            tags=tags,
        )
        config.models.append(model)
        config.save()
        typer.echo(f"Added model: backend_id={backend_id}, provider={provider_id}, model_id={model_id}")
    except Exception as exc:
        typer.echo(f"Error adding model: {exc}", err=True)
        raise typer.Exit(code=1)

@model_app.command("list")
def model_list(
    alias: str = typer.Option(..., "--alias", "-a", help="Workspace alias")
):
    """List all backend models defined in the workspace."""
    try:
        config = _load_workspace(alias)
        if not config.models:
            typer.echo("No models registered.")
            return
        for m in config.models:
            tags_str = ", ".join(m.tags) if m.tags else ""
            typer.echo(f"{m.backend_id}: provider={m.provider_id}, model_id={m.model_id}, tags=[{tags_str}]")
    except Exception as exc:
        typer.echo(f"Error listing models: {exc}", err=True)
        raise typer.Exit(code=1)

@model_app.command("remove")
def model_remove(
    backend_id: str,
    alias: str = typer.Option(..., "--alias", "-a", help="Workspace alias")
):
    """Remove a backend model from the workspace configuration."""
    try:
        config = _load_workspace(alias)
        original_len = len(config.models)
        config.models = [m for m in config.models if m.backend_id != backend_id]
        if len(config.models) == original_len:
            typer.echo(f"No model with backend_id '{backend_id}' found.", err=True)
            raise typer.Exit(code=1)
        config.save()
        typer.echo(f"Removed model '{backend_id}'.")
    except Exception as exc:
        typer.echo(f"Error removing model: {exc}", err=True)
        raise typer.Exit(code=1)

if __name__ == "__main__":
    app()


app = typer.Typer()


def main():
    """Entry point for the CLI when invoked via console script."""
    app()

@app.command()
def hello(name: str = "world"):
    """Simple hello command for testing the CLI entrypoint."""
    typer.echo(f"Hello, {name}!")

if __name__ == "__main__":
    app()
