import typer
import asyncio
from my_model.router.client import VSRClient
from typing import List, Optional

from my_model.config import WorkspaceConfig, ModelConfig, RouterConfig, ProviderConfig
from pydantic import SecretStr

app = typer.Typer()
model_app = typer.Typer()
app.add_typer(model_app, name="model")

def _load_workspace(alias: str) -> WorkspaceConfig:
    """Load workspace configuration for given alias."""
    return WorkspaceConfig.load(alias)

@app.command()
def hello(name: str = "world"):
    """Simple hello command for testing the CLI entrypoint."""
    typer.echo(f"Hello, {name}!")

# ===== Model subcommands (unchanged) =====
@model_app.command("add")
def model_add(
    alias: str = typer.Option(..., "--alias", "-a", help="Workspace alias"),
    provider_id: str = typer.Option(..., "--provider-id", "-p", help="Provider identifier defined in workspace"),
    model_id: str = typer.Option(..., "--model-id", "-m", help="Backend model identifier for the provider"),
    tags: List[str] = typer.Option([], "--tag", "-t", help="Tag for the model (repeatable)"),
    backend_id: Optional[str] = typer.Option(None, "--backend-id", help="Unique backend ID (optional, autogenerated)"),
):
    """Add a backend model to the workspace configuration."""
    try:
        config = _load_workspace(alias)
        if not any(p.provider_id == provider_id for p in config.providers):
            typer.echo(f"Provider '{provider_id}' not found in workspace '{alias}'.", err=True)
            raise typer.Exit(code=1)
        if not backend_id:
            backend_id = f"{provider_id}-{model_id}"
        if any(m.backend_id == backend_id for m in config.models):
            typer.echo(f"Model with backend_id '{backend_id}' already exists.", err=True)
            raise typer.Exit(code=1)

        model = ModelConfig(
            backend_id=backend_id,
            provider_id=provider_id,
            model_id=model_id,
            tags=tags,
        )
        config.models.append(model)
        config.save()
        typer.echo(f"Added model: backend_id={backend_id}, provider={provider_id}, model_id={model_id}")
    except Exception as exc:
        typer.echo(f"Error adding model: {exc}", err=True)
        raise typer.Exit(code=1)

@model_app.command("list")
def model_list(
    alias: str = typer.Option(..., "--alias", "-a", help="Workspace alias")
):
    """List all backend models defined in the workspace."""
    try:
        config = _load_workspace(alias)
        if not config.models:
            typer.echo("No models registered.")
            return
        for m in config.models:
            tags_str = ", ".join(m.tags) if m.tags else ""
            typer.echo(f"{m.backend_id}: provider={m.provider_id}, model_id={m.model_id}, tags=[{tags_str}]")
    except Exception as exc:
        typer.echo(f"Error listing models: {exc}", err=True)
        raise typer.Exit(code=1)

@model_app.command("remove")
def model_remove(
    backend_id: str,
    alias: str = typer.Option(..., "--alias", "-a", help="Workspace alias")
):
    """Remove a backend model from the workspace configuration."""
    try:
        config = _load_workspace(alias)
        original_len = len(config.models)
        config.models = [m for m in config.models if m.backend_id != backend_id]
        if len(config.models) == original_len:
            typer.echo(f"No model with backend_id '{backend_id}' not found.", err=True)
            raise typer.Exit(code=1)
        config.save()
        typer.echo(f"Removed model '{backend_id}'.")
    except Exception as exc:
        typer.echo(f"Error removing model: {exc}", err=True)
        raise typer.Exit(code=1)

# ===== Provider subcommands =====
provider_app = typer.Typer()
app.add_typer(provider_app, name="provider")

@provider_app.command("add")
def provider_add(
    alias: str = typer.Option(..., "--alias", "-a", help="Workspace alias"),
    provider_id: str = typer.Option(..., "--provider-id", "-p", help="Provider identifier"),
    base_url: str = typer.Option(..., "--base-url", "-b", help="Base URL of the provider"),
    api_key: str = typer.Option("", "--api-key", hide_input=True, help="API key (optional)"),
):
    """Add a provider to the workspace configuration."""
    try:
        config = _load_workspace(alias)
        if any(p.provider_id == provider_id for p in config.providers):
            typer.echo(f"Provider '{provider_id}' already exists.", err=True)
            raise typer.Exit(code=1)
        provider_cfg = ProviderConfig(
            provider_id=provider_id,
            base_url=base_url,
            api_key=SecretStr(api_key) if api_key else None,
        )
        config.providers.append(provider_cfg)
        config.save()
        typer.echo(f"Added provider '{provider_id}'.")
    except Exception as exc:
        typer.echo(f"Error adding provider: {exc}", err=True)
        raise typer.Exit(code=1)

@provider_app.command("list")
def provider_list(
    alias: str = typer.Option(..., "--alias", "-a", help="Workspace alias")
):
    """List all providers in the workspace configuration."""
    try:
        config = _load_workspace(alias)
        if not config.providers:
            typer.echo("No providers registered.")
            return
        for p in config.providers:
            key_display = "*****" if p.api_key else "(none)"
            typer.echo(f"{p.provider_id}: base_url={p.base_url}, api_key={key_display}")
    except Exception as exc:
        typer.echo(f"Error listing providers: {exc}", err=True)
        raise typer.Exit(code=1)

@provider_app.command("remove")
def provider_remove(
    provider_id: str,
    alias: str = typer.Option(..., "--alias", "-a", help="Workspace alias")
):
    """Remove a provider from the workspace configuration."""
    try:
        config = _load_workspace(alias)
        original_len = len(config.providers)
        config.providers = [p for p in config.providers if p.provider_id != provider_id]
        if len(config.providers) == original_len:
            typer.echo(f"Provider '{provider_id}' not found.", err=True)
            raise typer.Exit(code=1)
        # Also remove any models that belong to this provider
        config.models = [m for m in config.models if m.provider_id != provider_id]
        config.save()
        typer.echo(f"Removed provider '{provider_id}'.")
    except Exception as exc:
        typer.echo(f"Error removing provider: {exc}", err=True)
        raise typer.Exit(code=1)
# ===== Init wizard =====
@app.command()
def init():
    """Interactive wizard to create a new workspace (virtual model)."""
    # Alias
    alias = typer.prompt("Enter a name for the virtual model (alias)", default="my-alias")

    # Router configuration
    default_vsr = "http://localhost:8888/v1/chat/completions"
    vsr_url = typer.prompt("VSR URL", default=default_vsr)
    mode = typer.prompt("VSR mode (headers/json)", default="headers")
    router_cfg = RouterConfig(vsr_url=vsr_url, mode=mode)

    # Initialize workspace config
    workspace = WorkspaceConfig(alias=alias, router=router_cfg)

    # Provider wizard loop
    while True:
        if not typer.confirm("Add a provider?", default=True):
            break
        # Choose provider id
        provider_options = ["openai", "regolo", "anthropic", "google", "xai", "openai-compatible"]
        provider_id = typer.prompt(f"Provider ID ({'/'.join(provider_options)})", default="openai")
        # Determine base URL defaults
        default_base = (
            "https://api.openai.com" if provider_id == "openai" else
            "https://api.regolo.ai/v1" if provider_id == "regolo" else
            "https://api.x.ai/v1" if provider_id == "xai" else ""
        )
        base_url = typer.prompt("Base URL", default=default_base) if default_base else typer.prompt("Base URL")
        api_key = typer.prompt("API key (leave blank if none)", hide_input=True, default="")
        api_key_secret = api_key if api_key else None
        provider_cfg = ProviderConfig(provider_id=provider_id, base_url=base_url, api_key=api_key_secret)
        workspace.providers.append(provider_cfg)

        # Model addition for this provider
        while True:
            if not typer.confirm(f"Add a backend model for provider '{provider_id}'?", default=False):
                break
            model_id = typer.prompt("Model ID (e.g., gpt-4o-mini)")
            tags_raw = typer.prompt("Tags (comma‑separated, optional)", default="")
            tags = [t.strip() for t in tags_raw.split(',')] if tags_raw else []
            backend_id = f"{provider_id}-{model_id}"
            model_cfg = ModelConfig(backend_id=backend_id, provider_id=provider_id, model_id=model_id, tags=tags)
            workspace.models.append(model_cfg)

    # Save workspace configuration
    workspace.save()
    typer.echo(f"Workspace '{alias}' created at {workspace._workspace_dir}")
    typer.echo(f"Run 'my-model serve --alias {alias}' to start the gateway.")

# ===== Serve command =====
@app.command()
def serve(
    alias: str = typer.Option(..., "--alias", "-a", help="Workspace alias"),
    host: str = typer.Option(None, "--host", help="Host to bind (default from config)"),
    port: int = typer.Option(None, "--port", help="Port to bind (default from config)"),
    log_level: str = typer.Option(None, "--log-level", help="Log level (default from config)"),
):
    """Start the local FastAPI gateway server."""
    import os
    try:
        config = WorkspaceConfig.load(alias)
    except Exception as exc:
        typer.echo(f"Error loading workspace config: {exc}", err=True)
        raise typer.Exit(code=1)

    # Set environment variables for core
    os.environ["VLLM_SR_URL"] = config.router.vsr_url
    # Set REGOLO_API_KEY to the first provider's key if any
    if config.providers:
        first_key = config.providers[0].api_key.get_secret_value() if config.providers[0].api_key else ""
        os.environ["REGOLO_API_KEY"] = first_key
    else:
        os.environ["REGOLO_API_KEY"] = ""

    # Resolve host/port/log_level
    host = host or config.gateway.host
    port = port or config.gateway.port
    log_level = log_level or config.gateway.log_level

    # Run the FastAPI app from core.py
    import uvicorn
    import my_model.gateway as gateway
    uvicorn.run(gateway.app, host=host, port=port, log_level=log_level)

# ===== Status command =====
@app.command()
def status(
    alias: str = typer.Option(..., "--alias", "-a", help="Workspace alias")
):
    """Show workspace configuration (masked) and basic checks."""
    try:
        config = WorkspaceConfig.load(alias)
    except Exception as exc:
        typer.echo(f"Error loading config: {exc}", err=True)
        raise typer.Exit(code=1)

    import json
    typer.echo("Workspace configuration:")
    typer.echo(json.dumps(config.masked_dict(), indent=2))

# ===== Doctor command =====
@app.command()
def doctor(
    alias: str = typer.Option(..., "--alias", "-a", help="Workspace alias"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Perform a test call to a provider (if possible)"),
):
    """Run diagnostics on the workspace configuration and components."""
    # Load workspace configuration
    try:
        config = WorkspaceConfig.load(alias)
    except Exception as exc:
        typer.echo(f"Error loading workspace config: {exc}", err=True)
        raise typer.Exit(code=1)

    errors = []

    # Check providers
    if not config.providers:
        errors.append("No providers configured in workspace.")
    else:
        missing_keys = [p.provider_id for p in config.providers if not p.api_key]
        if missing_keys:
            typer.echo(f"Warning: Providers missing API key: {', '.join(missing_keys)}", err=True)

    # Check models
    if not config.models:
        errors.append("No backend models configured in workspace.")

    # Ping VSR router
    try:
        client = VSRClient(vsr_url=config.router.vsr_url, mode=config.router.mode, timeout=config.router.timeout)
        selected = asyncio.run(client.get_selected_model([{"role": "system", "content": "ping"}]))
        # Close client
        asyncio.run(client.close())
        if not selected:
            errors.append("Router VSR did not return a selected model (empty response).")
        else:
            typer.echo(f"Router reachable, selected model: {selected}")
    except Exception as exc:
        errors.append(f"Failed to contact VSR router: {exc}")

    # Optional dry-run test call to a provider (only for mock provider)
    if dry_run:
        try:
            provider_cfg = None
            for p in config.providers:
                if p.provider_id == "mock":
                    provider_cfg = p
                    break
            if provider_cfg is None:
                provider_cfg = config.providers[0] if config.providers else None
            if provider_cfg:
                # Instantiate provider
                from my_model.gateway import _get_provider_instance
                provider = _get_provider_instance(provider_cfg)
                # Send a simple hello message (non-stream)
                response = asyncio.run(provider.chat_completions([{"role": "user", "content": "hello"}], model="dummy", stream=False))
                typer.echo("Dry-run provider call succeeded.")
            else:
                typer.echo("No provider available for dry-run.", err=True)
        except Exception as exc:
            errors.append(f"Dry-run provider call failed: {exc}")

    if errors:
        typer.echo("Doctor check failed:", err=True)
        for e in errors:
            typer.echo(f"- {e}", err=True)
        raise typer.Exit(code=1)

    typer.echo("All checks passed.")
    raise typer.Exit(code=0)

# ===== Entry point =====
def main():
    """Entry point for the CLI when invoked via console script."""
    app()
# Duplicate main removed

if __name__ == "__main__":
    app()

